# Generated by Django 5.0.2 on 2024-02-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_questiontype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='order',
        ),
    ]
